apiVersion: v1
kind: Namespace
metadata:
  name: cibera2

---
apiVersion: v1
kind: Secret
metadata:
  name: cibera2-secret
  namespace: cibera2
type: Opaque
data:
  DB_USERNAME: Z3J1cG8yYQ==
  DB_PASSWORD: Z3J1cG8yYQ==
  DB_DATABASE: Y2liZXI=
  DB_HOST: bWFyaWFkYg==
  DB_PORT: MzM2MA==
  PORT: ODA4MA==
  HOST: MC4wLjAuMA==
  MYSQL_ROOT_PASSWORD: MC4wLjAuMA==
  MYSQL_DATABASE: Y2liZXI=
  MYSQL_USER: Z3J1cG8yYQ==
  MYSQL_PASSWORD: Z3J1cG8yYQ==